# Generated by Django 4.0.2 on 2022-08-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.PositiveBigIntegerField(choices=[(0, 'Staff'), (1, 'EMIU Staff'), (2, 'Energy Resources Department'), (3, 'Distribution Services Department'), (4, 'Investment & Sector Development'), (5, 'Renewable Energy Department'), (6, 'Transmission Department'), (7, 'Management Staff')], default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
    ]
