# Generated by Django 4.0.2 on 2022-02-17 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('company', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('award_date', models.DateField()),
                ('proposed_completion_date', models.DateField()),
                ('contract_sum_ngn', models.DecimalField(decimal_places=3, max_digits=25)),
                ('contract_sum_usd', models.DecimalField(decimal_places=3, max_digits=25)),
                ('consultant', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.state')),
            ],
        ),
    ]
