# Generated by Django 4.0.2 on 2022-02-20 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_sum_ngn',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_sum_usd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True),
        ),
    ]
