# Generated by Django 4.0.2 on 2022-08-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_contract_sum_ngn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.PositiveIntegerField(choices=[(0, 'Energy Resources Department'), (1, 'Distribution Services Department'), (2, 'Investment & Sector Development'), (3, 'Renewable Energy Department'), (4, 'Transmission Department')]),
        ),
    ]
