# Generated by Django 4.0.2 on 2022-08-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.PositiveBigIntegerField(choices=[(0, 'Progress Payment - (IPC)'), (1, 'Retention'), (2, 'Contract VariationContingency')], default=0)),
                ('amount_paid_ngn', models.DecimalField(decimal_places=5, max_digits=50)),
                ('amount_paid_usd', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('amount_certified_ngn', models.DecimalField(decimal_places=5, max_digits=50)),
                ('amount_certified_usd', models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
