# Generated by Django 4.0.2 on 2022-02-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField()),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
            ],
        ),
    ]
