# Generated by Django 4.0.2 on 2022-02-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200, null=True)),
                ('alias', models.CharField(max_length=5, null=True)),
                ('room_number', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
